#!/bin/sh

case "$1" in
    lock)
        /opt/i3lock-fancy/lock -pt "Type password to unlock" -- maim
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        /opt/i3lock-fancy/lock && systemctl suspend
        ;;
    hibernate)
        /opt/i3lock-fancy/lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
