;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        c-electric-colon
        delete-indentation
        electric-newline-and-maybe-indent
        elpy-nav-backward-indent
        elpy-nav-forward-indent
        end-of-visual-line
        indent-for-tab-command
        kill-region
        multiple-cursors-hydra/ignore
        multiple-cursors-hydra/nil
        sp-backward-unwrap-sexp
        tex-handle-newline
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        centaur-tabs-forward
        multiple-cursors-hydra/body
        multiple-cursors-hydra/mc/add-cursor-on-click
        multiple-cursors-hydra/mc/cycle-backward
        multiple-cursors-hydra/mc/insert-numbers-and-exit
        multiple-cursors-hydra/mc/mark-all-like-this-and-exit
        multiple-cursors-hydra/mc/mark-next-like-this
        yaml-electric-dash-and-dot
        ))
