;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        c-electric-colon
        electric-newline-and-maybe-indent
        elpy-nav-backward-indent
        elpy-nav-forward-indent
        end-of-visual-line
        indent-for-tab-command
        kill-region
        sp-backward-unwrap-sexp
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
