;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        elpy-nav-backward-indent
        elpy-nav-forward-indent
        end-of-visual-line
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        ))
